# Generated by Django 3.2.19 on 2026-05-13 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0005_seatreservation_created_at'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='payment',
            name='movies_paym_razorpa_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='movies_paym_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='seatreservation',
            name='movies_reservation_expires_idx',
        ),
        migrations.RemoveField(
            model_name='seatreservation',
            name='reserved_at',
        ),
        migrations.AlterField(
            model_name='payment',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, help_text='Set after the user completes payment.', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='seatreservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['razorpay_order_id'], name='movies_paym_razorpa_39457f_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'created_at'], name='movies_paym_status_8acdf7_idx'),
        ),
        migrations.AddIndex(
            model_name='seatreservation',
            index=models.Index(fields=['expires_at'], name='movies_seat_expires_b885cc_idx'),
        ),
    ]
