# Generated by Django 3.2.19 on 2026-05-18 01:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import movies.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0008_genre_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='movies_paym_razorpa_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='movies_paym_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='seatreservation',
            name='movies_reservation_expires_idx',
        ),
        migrations.RemoveField(
            model_name='seatreservation',
            name='reserved_at',
        ),
        migrations.AddField(
            model_name='movie',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(help_text='Auto-generated from name. Used in filter URLs.', unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(help_text="ISO 639-1 code, e.g. 'hi', 'en', 'te'", max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='movies', to='movies.Genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='movies', to='movies.Language'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, help_text='YouTube trailer URL — only valid YouTube links accepted.', null=True, validators=[movies.models.validate_youtube_url]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount_paise',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='seat_ids',
            field=models.JSONField(help_text='Seat PKs in this payment.'),
        ),
        migrations.AlterField(
            model_name='seatreservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['name'], name='movie_name_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['razorpay_order_id'], name='payment_order_idx'),
        ),
        migrations.AddIndex(
            model_name='seatreservation',
            index=models.Index(fields=['expires_at'], name='reservation_expires_idx'),
        ),
        migrations.AddIndex(
            model_name='theater',
            index=models.Index(fields=['movie'], name='theater_movie_idx'),
        ),
    ]
